from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO


def generate_pdf(data):

    buffer = BytesIO()

    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    y = height - 50

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Research Sentinel AI Report")

    y -= 40

    c.setFont("Helvetica", 12)

    # Title
    c.drawString(50, y, f"Title: {data['title']}")
    y -= 20

    # Abstract
    c.drawString(50, y, "Abstract:")
    y -= 20

    for line in data["abstract"][:120].split("."):
        c.drawString(70, y, line.strip())
        y -= 15

    y -= 20

    # Score
    c.drawString(50, y, "Final Decision Report")
    y -= 20

    c.drawString(70, y, f"Score: {data['score']}")
    y -= 20

    c.drawString(70, y, f"Decision: {data['decision']}")

    y -= 40

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y, "Generated by Research Sentinel AI")

    c.save()

    buffer.seek(0)

    return buffer 